### ISSUE TITLE
Dependency ordering is not supported

### ISSUE THREAD

**Issue by adamMeeruTech** [simplesurance/baur#149]
When defining the Build Inputs, the defined paths are not built in any sort of meaningful order. 

In the example below, I expect to have the shared path get built first, and then my application in '.'

```
  [Build.Input.GitFiles]
    paths = ["../shared", "."]
```

Is there a way to accomplish dependency ordering that maybe i'm just missing?

Thanks!

**Comment by fho** [comment]
No, baur currently does not support build dependencies.
The Build Inputs only specify the files that are hashed to describe the current state of the application source files.
When the hash changes, the application is rebuild. 

Other build tools exist that support to specify build dependencies, maybe 
please (https://please.build), bazel or pants does what you are looking for?

**Comment by fho** [comment]
Related discussion: https://github.com/simplesurance/baur/issues/154
