### ISSUE TITLE
Remove use of pkg/errors 

### ISSUE THREAD

**Issue by fho** [simplesurance/baur#211]
Support to wrap errors was used in Go.
In the master branch most packages already were changed to use Golangs error wrapping technique instead of pkg/errors.

Replace all remaining usages of pkg/errors with using Golangs errors wrapper technique (`fmt.Errorf("msg: %w ",err)`).

**Comment by u5surf** [comment]
@fho Hi, Can I work on this issue?
I’m sure where should I fix.
```
~/baur grep -rn "pkg/error" --include '*.go' . | grep -v vendor
./internal/upload/filecopy/filecopy.go:8:"github.com/pkg/errors"
./internal/upload/docker/docker.go:9:"github.com/pkg/errors"
./internal/version/version.go:7:"github.com/pkg/errors"
./internal/vcs/git/git.go:13:"github.com/pkg/errors"
./internal/fs/fileglob.go:8:"github.com/pkg/errors"
./internal/digest/digest.go:8:"github.com/pkg/errors"
./internal/digest/sha384/sha384.go:11:"github.com/pkg/errors"
./repository.go:7:"github.com/pkg/errors"
./app.go:7:"github.com/pkg/errors"

```

**Comment by fho** [comment]
@u5surf yes, would be great if you can implement it.

All occurrences needs to be changed. There should be no `github.com/pkg/errors` import in the master branch anymore and the package should be removed from go.mod and the vendor directory
