### ISSUE TITLE
baur diff: add input-str and lookup-input-str functionality to diff command

### ISSUE THREAD

**Issue by dbason** [simplesurance/baur#232]
The input str and diff commands are both looking really good, there is just one more piece to help round out our use case (https://github.com/simplesurance/baur/issues/117)

We would like to combine the two so that we can also use the input-str functionality when we are diffing the last build.  The two pieces of functionality would be:

- When input-str is added using the carrot(^) notation it will look up the builds with the input-str.  The diff will then use the input str to do the comparison
- When lookup-input-str is provided if no previous build is found with the input-str it will then do the search using the lookup-input-str.  For the purposes of comparison both the previous build and the current working directory will use the input-str.

Please let me know if anything needs further clarification

**Comment by StephenDiligent** [comment]
@fho This issue has been addressed by the changes in [Add input-str and limit filtering to ls runs command](https://github.com/simplesurance/baur/pull/239 ).
We now have all of the required changes to address our use case. When can we expect the next release to be published?
FYI @dbrougham

**Comment by fho** [comment]
@StephenDiligent hard to tell, depends on how many other more important things will come up at my work. :-)

All the major changes are implemented. There are only some smaller things left that I'll finish in the next days (https://github.com/simplesurance/baur/milestone/1).
I aim to have a first `-rc` release until end of the month. We will then already migrate our companies internal CI workflow to the new version and start to use it.
