### ISSUE TITLE
diff inputs - Does not accept an app name that contains a dash '-'

### ISSUE THREAD

**Issue by dbrougham** [simplesurance/baur#236]
Hi,

When using the `diff inputs` command with an application name that contains a dash the command will throw an error.

Command: `baur diff inputs application-one.build application-one.build^`

![image](https://user-images.githubusercontent.com/3860517/102032431-9a61b380-3e1d-11eb-9ce1-a41aac490d7e.png)

If I rename the inputs to `application_one.build` the command will resolve correctly.

Command: `baur diff inputs application_one.build application_one.build^`

![image](https://user-images.githubusercontent.com/3860517/102032685-5de28780-3e1e-11eb-9b9f-d48f963d760f.png)

Have narrowed down the root cause to the regex expression used here: https://github.com/simplesurance/baur/blob/ba560e8f282c67f673ff865ce58a7f46e8a52ada/internal/command/diff_inputs.go#L112

My question is what additional characters should also be supported? Or should it allow any characters followed by a single period and then the task name?

**Comment by fho** [comment]
Hello David,

thanks for the report. 
That is a bug, dashes should be supported supported in app and task names

> My question is what additional characters should also be supported? Or should it allow any characters followed by a single period and then the task name?

I would suggest `[\w-]+` for app and task names
