### ISSUE TITLE
Can applications tasks be run parallel?

### ISSUE THREAD

**Issue by thomsa** [simplesurance/baur#331]
Can we make applications run in parallel mode? 

Because it takes quite a long time to run all the apps sequentially, if you could point out the part where the execution could be run in a parallel way I would even contribute to the repo.

**Comment by fho** [comment]
It's already supported in the master branch (https://github.com/simplesurance/baur/commit/77a235a1f0505e1787393843a4c1d178dcec0f81).
There is only no release with it yet.

You can build+install it via `go install github.com/simplesurance/baur/v2/...@master` and run tasks in parallel like `baur run --parallel-runs 4`.

I planned to create a release as soon as https://github.com/simplesurance/baur/issues/319 fixed but I'm currently busy with another project.
