### ISSUE TITLE
Possibility to tag image without building it

### ISSUE THREAD

**Issue by thomsa** [simplesurance/baur#340]
Hi! 

Is there a possibility to tag the latest image with a given tag without actually executing anything?

The scenario:
- We have `main` branch that is always built after every push and it ends up being a docker image: `my-image:main`
- Relases are just tags on main, the way we can upload them is  to specify `--input-str vx.x.x.` and have the same `vx.x.x.` as an env variable so that baur can tag the new image with `my-image:vx.x.x.`

The problem with this approach is that the images are constantly rebuilt, while the latest tagged version from main is exactly the same as the newest release. 

Is there a possibility to have the upload part executed without actually having to run the task in the task definition?

**Comment by fho** [comment]
Hello @thomsa,

> Is there a possibility to have the upload part executed without actually having to run the task in the task definition?

No that is currently not possible.

Does it maybe work to create a baur task that runs a custom bash script and the bash script does only the tagging/uploading?

**Comment by fho** [comment]
closing, no answer from issue author
