### ISSUE TITLE
fileglob resolver: use WithFilesOnly option for doublestar.FilepathGlob

### ISSUE THREAD

**Issue by fho** [simplesurance/baur#418]
doublestar supports a new option to only return files as results.
Use that option instead of filtering out all dirs on our own fs/fileglob.go

https://github.com/bmatcuk/doublestar/releases/tag/v4.5.0

**Comment by prachurjya15** [comment]
Hi @fho, I would like to take this up. Can you please assign to me.

**Comment by fho** [comment]
@prachurjya15 awesome, thanks!
 I assigned the issue to you.
