### ISSUE TITLE
Configuring .app.toml to use GCR Docker Repositories as a Docker Registry doesn't work 

### ISSUE THREAD

**Issue by nicodoggie** [simplesurance/baur#96]
In our environment, we use Google Cloud Repository to house our docker images, and the URI path does not necessarily conform to the assumptions made in the `parseRepositoryURI` function.

The code assumes a URI in the format `[<host[:port]>]/<owner>/<repository>:<tag>`, but in GCR the paths are much more flexible.

In our case we have something like `gcr.io/department/service-type/application:tag` instead.

Code in question:
https://github.com/simplesurance/baur/blob/cc5c3b13dae0671c0660689601111764b16baca7/upload/docker/docker.go#L150-L158

I get that the assumption conforms to `hub.docker.com`'s URI format, but it makes baur unable to support private docker repositories that do not conform to this format. 

Then, event if I conform to the format enforced by that code, it seems that `~/.docker/config.json` file isn't being respected anyway, whether or not the `DOCKER_CONFIG` environment variable is set. I haven't investigated that yet, however.

**Comment by fho** [comment]
@nicodoggie thanks for the report.

Are you using the `Domain-scoped projects` syntax (https://cloud.google.com/container-registry/docs/overview#domain-scoped_projects)?
According to their documentation the syntax in deprecated.

**Comment by nicodoggie** [comment]
No, as I described, we scope things by department and service type
Something like:
`gcr.io/ops-team/scheduled/runner:deadbeef12341234`

**Comment by fho** [comment]
@nicodoggie that looks like the `Domain-scoped projects´ syntax.
If it's not, can you please provide a link to the GCR or better docker documentation that describes this syntax?
thanks

**Comment by nicodoggie** [comment]
I don't really see it documented anywhere, but GCR does allow to push into arbitrarily long paths into gcr.io

`docker push gcr.io/project-id/service-type/repo:tag`
`docker push gcr.io/project-id/service-type/whatever/repo:tag`

is actually acceptable, and is used across the board in our infrastructure. I've added a PR for a proposed fix.

**Comment by fho** [comment]
@nicodoggie 
Thanks for the PR.

I still would like to have a reference for this syntax. It's not mentioned in documentation for docker.

Why do you think it is not the https://cloud.google.com/container-registry/docs/overview#domain-scoped_projects syntax?

`[HOSTNAME]/[DOMAIN]/[PROJECT]/[IMAGE]`
matches
`gcr.io/project-id/service-type/repo`
` gcr.io/ops-team/scheduled/runner`

**Comment by nicodoggie** [comment]
Well, it is similar, but we don't actually put a domain at all, so it's technically not domain-scoped. 
Also, it isn't limited to 3 levels of nesting deep, necessarily.

Would it be enough to temporarily upload an example repository image?

**Comment by fho** [comment]
@nicodoggie ok, makes sense

I found a reference https://github.com/docker/distribution/blob/master/docs/spec/api.md#overview
> If a repository name has two or more path components, they must be separated by a forward slash ("/").

**Comment by nicodoggie** [comment]
Getting this error: `failed: Docker upload failed: API error (400): Bad parameters and missing X-Registry-Auth: EOF`
I've yet to start investigating if this is due to a config issue on my end, or something in baur though

**Comment by nicodoggie** [comment]
Got GCR push to work now. It was failing because baur doesn't support `docker/config.json` configured with just gcloud as a credential helper (see https://cloud.google.com/container-registry/docs/advanced-authentication). I had to configure with an access token.

`gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io`

**Comment by fho** [comment]
@nicodoggie great, thanks for the feedback!

I'll add a note to the wiki that credentials helpers are not supported (the docker lib that baur uses supports it neither https://github.com/fsouza/go-dockerclient/issues/627)
